{"uid":"d0c1f6956680ea49","name":"test_send_message","fullName":"tests.test_example.ExampleTestCase#test_send_message","historyId":"3bc4f3765c9b31fcf733254dd25c049d","time":{"start":1757402720501,"stop":1757402722765,"duration":2264},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_send_message>\n\n    def test_send_message(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fa0ecf2eb90>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"Reached error page: about:neterror?e=connection....sys.mjs:156:19\\\\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nE       UnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\nE       checkReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nE       onNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nE       emit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nE       receiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1757402714570,"stop":1757402714570,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1757402722788,"stop":1757402722788,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"2663-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"2c87436a0af6ff7f","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=140.0.7339.80)\nStacktrace:\n#0 0x562bfc5ac94a <unknown>\n#1 0x562bfc0218a0 <unknown>\n#2 0x562bfc018ce8 <unknown>\n#3 0x562bfc00a1b6 <unknown>\n#4 0x562bfc00bf00 <unknown>\n#5 0x562bfc00a55e <unknown>\n#6 0x562bfc009ee7 <unknown>\n#7 0x562bfc009bc5 <unknown>\n#8 0x562bfc007a42 <unknown>\n#9 0x562bfc00822a <unknown>\n#10 0x562bfc024db9 <unknown>\n#11 0x562bfc0bf835 <unknown>\n#12 0x562bfc099032 <unknown>\n#13 0x562bfc0bec23 <unknown>\n#14 0x562bfc098e03 <unknown>\n#15 0x562bfc065968 <unknown>\n#16 0x562bfc0665e1 <unknown>\n#17 0x562bfc570548 <unknown>\n#18 0x562bfc574272 <unknown>\n#19 0x562bfc557313 <unknown>\n#20 0x562bfc574dc5 <unknown>\n#21 0x562bfc53c49f <unknown>\n#22 0x562bfc599158 <unknown>\n#23 0x562bfc599332 <unknown>\n#24 0x562bfc5aba53 <unknown>\n#25 0x7ff594a9caa4 <unknown>\n#26 0x7ff594b29c3c <unknown>","time":{"start":1757402717606,"stop":1757402718205,"duration":599}},{"uid":"a58f0e181cc2d37f","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757402709688,"stop":1757402712280,"duration":2592}},{"uid":"b8d7d6a9f5df1b3b","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757402707507,"stop":1757402709669,"duration":2162}},{"uid":"56128f820333c3a1","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x5598ff1ec08a <unknown>\n#1 0x5598fec8ba70 <unknown>\n#2 0x5598fec82cf1 <unknown>\n#3 0x5598fec74099 <unknown>\n#4 0x5598fec75de0 <unknown>\n#5 0x5598fec7443e <unknown>\n#6 0x5598fec73daa <unknown>\n#7 0x5598fec73a85 <unknown>\n#8 0x5598fec718ee <unknown>\n#9 0x5598fec720ca <unknown>\n#10 0x5598fec8ef99 <unknown>\n#11 0x5598fed29d65 <unknown>\n#12 0x5598fed033e2 <unknown>\n#13 0x5598fed2914f <unknown>\n#14 0x5598fed031b3 <unknown>\n#15 0x5598feccf59b <unknown>\n#16 0x5598fecd0971 <unknown>\n#17 0x5598ff1b125b <unknown>\n#18 0x5598ff1b4fa9 <unknown>\n#19 0x5598ff198339 <unknown>\n#20 0x5598ff1b5b58 <unknown>\n#21 0x5598ff17cc1f <unknown>\n#22 0x5598ff1d9118 <unknown>\n#23 0x5598ff1d92f6 <unknown>\n#24 0x5598ff1eb066 <unknown>\n#25 0x7fb68b49caa4 <unknown>\n#26 0x7fb68b529c3c <unknown>","time":{"start":1757402703764,"stop":1757402704432,"duration":668}},{"uid":"ed96ae7832c72160","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x5615c32fb08a <unknown>\n#1 0x5615c2d9aa70 <unknown>\n#2 0x5615c2d91cf1 <unknown>\n#3 0x5615c2d83099 <unknown>\n#4 0x5615c2d84de0 <unknown>\n#5 0x5615c2d8343e <unknown>\n#6 0x5615c2d82daa <unknown>\n#7 0x5615c2d82a85 <unknown>\n#8 0x5615c2d808ee <unknown>\n#9 0x5615c2d810ca <unknown>\n#10 0x5615c2d9df99 <unknown>\n#11 0x5615c2e38d65 <unknown>\n#12 0x5615c2e123e2 <unknown>\n#13 0x5615c2e3814f <unknown>\n#14 0x5615c2e121b3 <unknown>\n#15 0x5615c2dde59b <unknown>\n#16 0x5615c2ddf971 <unknown>\n#17 0x5615c32c025b <unknown>\n#18 0x5615c32c3fa9 <unknown>\n#19 0x5615c32a7339 <unknown>\n#20 0x5615c32c4b58 <unknown>\n#21 0x5615c328bc1f <unknown>\n#22 0x5615c32e8118 <unknown>\n#23 0x5615c32e82f6 <unknown>\n#24 0x5615c32fa066 <unknown>\n#25 0x7fd3af89caa4 <unknown>\n#26 0x7fd3af929c3c <unknown>","time":{"start":1757402703204,"stop":1757402703870,"duration":666}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d0c1f6956680ea49.json","parameterValues":[]}