{"uid":"5c928bc17d02f2fb","name":"test_page_title","fullName":"tests.test_example.ExampleTestCase#test_page_title","historyId":"1f00af4742c2562b8d24e8127e7405ec","time":{"start":1757403372457,"stop":1757403373236,"duration":779},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55f71023108a <unknown>\n#1 0x55f70fcd0a70 <unknown>\n#2 0x55f70fcc7cf1 <unknown>\n#3 0x55f70fcb9099 <unknown>\n#4 0x55f70fcbade0 <unknown>\n#5 0x55f70fcb943e <unknown>\n#6 0x55f70fcb8daa <unknown>\n#7 0x55f70fcb8a85 <unknown>\n#8 0x55f70fcb68ee <unknown>\n#9 0x55f70fcb70ca <unknown>\n#10 0x55f70fcd3f99 <unknown>\n#11 0x55f70fd6ed65 <unknown>\n#12 0x55f70fd483e2 <unknown>\n#13 0x55f70fd6e14f <unknown>\n#14 0x55f70fd481b3 <unknown>\n#15 0x55f70fd1459b <unknown>\n#16 0x55f70fd15971 <unknown>\n#17 0x55f7101f625b <unknown>\n#18 0x55f7101f9fa9 <unknown>\n#19 0x55f7101dd339 <unknown>\n#20 0x55f7101fab58 <unknown>\n#21 0x55f7101c1c1f <unknown>\n#22 0x55f71021e118 <unknown>\n#23 0x55f71021e2f6 <unknown>\n#24 0x55f710230066 <unknown>\n#25 0x7f97aa89caa4 <unknown>\n#26 0x7f97aa929c3c <unknown>","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_page_title>\n\n    def test_page_title(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe93875cf50>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x55f710230066 \\\\u003Cunknown>\\\\n#25 0x7f97aa89caa4 \\\\u003Cunknown>\\\\n#26 0x7f97aa929c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=139.0.7258.154)\nE       Stacktrace:\nE       #0 0x55f71023108a <unknown>\nE       #1 0x55f70fcd0a70 <unknown>\nE       #2 0x55f70fcc7cf1 <unknown>\nE       #3 0x55f70fcb9099 <unknown>\nE       #4 0x55f70fcbade0 <unknown>\nE       #5 0x55f70fcb943e <unknown>\nE       #6 0x55f70fcb8daa <unknown>\nE       #7 0x55f70fcb8a85 <unknown>\nE       #8 0x55f70fcb68ee <unknown>\nE       #9 0x55f70fcb70ca <unknown>\nE       #10 0x55f70fcd3f99 <unknown>\nE       #11 0x55f70fd6ed65 <unknown>\nE       #12 0x55f70fd483e2 <unknown>\nE       #13 0x55f70fd6e14f <unknown>\nE       #14 0x55f70fd481b3 <unknown>\nE       #15 0x55f70fd1459b <unknown>\nE       #16 0x55f70fd15971 <unknown>\nE       #17 0x55f7101f625b <unknown>\nE       #18 0x55f7101f9fa9 <unknown>\nE       #19 0x55f7101dd339 <unknown>\nE       #20 0x55f7101fab58 <unknown>\nE       #21 0x55f7101c1c1f <unknown>\nE       #22 0x55f71021e118 <unknown>\nE       #23 0x55f71021e2f6 <unknown>\nE       #24 0x55f710230066 <unknown>\nE       #25 0x7f97aa89caa4 <unknown>\nE       #26 0x7f97aa929c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1757403346448,"stop":1757403346448,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1757403374053,"stop":1757403374053,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"2613-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"78866173cdfc17f3","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55c7f9c4808a <unknown>\n#1 0x55c7f96e7a70 <unknown>\n#2 0x55c7f96decf1 <unknown>\n#3 0x55c7f96d0099 <unknown>\n#4 0x55c7f96d1de0 <unknown>\n#5 0x55c7f96d043e <unknown>\n#6 0x55c7f96cfdaa <unknown>\n#7 0x55c7f96cfa85 <unknown>\n#8 0x55c7f96cd8ee <unknown>\n#9 0x55c7f96ce0ca <unknown>\n#10 0x55c7f96eaf99 <unknown>\n#11 0x55c7f9785d65 <unknown>\n#12 0x55c7f975f3e2 <unknown>\n#13 0x55c7f978514f <unknown>\n#14 0x55c7f975f1b3 <unknown>\n#15 0x55c7f972b59b <unknown>\n#16 0x55c7f972c971 <unknown>\n#17 0x55c7f9c0d25b <unknown>\n#18 0x55c7f9c10fa9 <unknown>\n#19 0x55c7f9bf4339 <unknown>\n#20 0x55c7f9c11b58 <unknown>\n#21 0x55c7f9bd8c1f <unknown>\n#22 0x55c7f9c35118 <unknown>\n#23 0x55c7f9c352f6 <unknown>\n#24 0x55c7f9c47066 <unknown>\n#25 0x7f76c9c9caa4 <unknown>\n#26 0x7f76c9d29c3c <unknown>","time":{"start":1757403360695,"stop":1757403361438,"duration":743}},{"uid":"1613aac422e83802","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757403353291,"stop":1757403356057,"duration":2766}},{"uid":"531830aae343efc3","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757403349855,"stop":1757403352070,"duration":2215}},{"uid":"dbc64340e45e7033","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x562ca8f6508a <unknown>\n#1 0x562ca8a04a70 <unknown>\n#2 0x562ca89fbcf1 <unknown>\n#3 0x562ca89ed099 <unknown>\n#4 0x562ca89eede0 <unknown>\n#5 0x562ca89ed43e <unknown>\n#6 0x562ca89ecdaa <unknown>\n#7 0x562ca89eca85 <unknown>\n#8 0x562ca89ea8ee <unknown>\n#9 0x562ca89eb0ca <unknown>\n#10 0x562ca8a07f99 <unknown>\n#11 0x562ca8aa2d65 <unknown>\n#12 0x562ca8a7c3e2 <unknown>\n#13 0x562ca8aa214f <unknown>\n#14 0x562ca8a7c1b3 <unknown>\n#15 0x562ca8a4859b <unknown>\n#16 0x562ca8a49971 <unknown>\n#17 0x562ca8f2a25b <unknown>\n#18 0x562ca8f2dfa9 <unknown>\n#19 0x562ca8f11339 <unknown>\n#20 0x562ca8f2eb58 <unknown>\n#21 0x562ca8ef5c1f <unknown>\n#22 0x562ca8f52118 <unknown>\n#23 0x562ca8f522f6 <unknown>\n#24 0x562ca8f64066 <unknown>\n#25 0x7f933289caa4 <unknown>\n#26 0x7f9332929c3c <unknown>","time":{"start":1757403349710,"stop":1757403350437,"duration":727}},{"uid":"33284ca3da18e8b8","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757403345551,"stop":1757403347725,"duration":2174}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5c928bc17d02f2fb.json","parameterValues":[]}