{"uid":"d81fc935bbd751d3","name":"test_send_message","fullName":"tests.test_example.ExampleTestCase#test_send_message","historyId":"3bc4f3765c9b31fcf733254dd25c049d","time":{"start":1757403373260,"stop":1757403374030,"duration":770},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x5567a688b08a <unknown>\n#1 0x5567a632aa70 <unknown>\n#2 0x5567a6321cf1 <unknown>\n#3 0x5567a6313099 <unknown>\n#4 0x5567a6314de0 <unknown>\n#5 0x5567a631343e <unknown>\n#6 0x5567a6312daa <unknown>\n#7 0x5567a6312a85 <unknown>\n#8 0x5567a63108ee <unknown>\n#9 0x5567a63110ca <unknown>\n#10 0x5567a632df99 <unknown>\n#11 0x5567a63c8d65 <unknown>\n#12 0x5567a63a23e2 <unknown>\n#13 0x5567a63c814f <unknown>\n#14 0x5567a63a21b3 <unknown>\n#15 0x5567a636e59b <unknown>\n#16 0x5567a636f971 <unknown>\n#17 0x5567a685025b <unknown>\n#18 0x5567a6853fa9 <unknown>\n#19 0x5567a6837339 <unknown>\n#20 0x5567a6854b58 <unknown>\n#21 0x5567a681bc1f <unknown>\n#22 0x5567a6878118 <unknown>\n#23 0x5567a68782f6 <unknown>\n#24 0x5567a688a066 <unknown>\n#25 0x7f64ed29caa4 <unknown>\n#26 0x7f64ed329c3c <unknown>","statusTrace":"self = <test_example.ExampleTestCase testMethod=test_send_message>\n\n    def test_send_message(self):\n>       self.home.open(OLLAMA_URL)\n\ntests/test_example.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages/home_page.py:21: in open\n    self.driver.get(url)\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:483: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py:458: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7fe93ab79dd0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x5567a688a066 \\\\u003Cunknown>\\\\n#25 0x7f64ed29caa4 \\\\u003Cunknown>\\\\n#26 0x7f64ed329c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=139.0.7258.154)\nE       Stacktrace:\nE       #0 0x5567a688b08a <unknown>\nE       #1 0x5567a632aa70 <unknown>\nE       #2 0x5567a6321cf1 <unknown>\nE       #3 0x5567a6313099 <unknown>\nE       #4 0x5567a6314de0 <unknown>\nE       #5 0x5567a631343e <unknown>\nE       #6 0x5567a6312daa <unknown>\nE       #7 0x5567a6312a85 <unknown>\nE       #8 0x5567a63108ee <unknown>\nE       #9 0x5567a63110ca <unknown>\nE       #10 0x5567a632df99 <unknown>\nE       #11 0x5567a63c8d65 <unknown>\nE       #12 0x5567a63a23e2 <unknown>\nE       #13 0x5567a63c814f <unknown>\nE       #14 0x5567a63a21b3 <unknown>\nE       #15 0x5567a636e59b <unknown>\nE       #16 0x5567a636f971 <unknown>\nE       #17 0x5567a685025b <unknown>\nE       #18 0x5567a6853fa9 <unknown>\nE       #19 0x5567a6837339 <unknown>\nE       #20 0x5567a6854b58 <unknown>\nE       #21 0x5567a681bc1f <unknown>\nE       #22 0x5567a6878118 <unknown>\nE       #23 0x5567a68782f6 <unknown>\nE       #24 0x5567a688a066 <unknown>\nE       #25 0x7f64ed29caa4 <unknown>\nE       #26 0x7f64ed329c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":5,"retriesStatusChange":false,"beforeStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase","time":{"start":1757403346448,"stop":1757403346448,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"_unittest_setUpClass_fixture_ExampleTestCase::0","time":{"start":1757403374053,"stop":1757403374053,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_example"},{"name":"subSuite","value":"ExampleTestCase"},{"name":"host","value":"pkrvm7jw40e0xgp"},{"name":"thread","value":"2613-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_example"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"7d481bebab8f5d59","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55579b21108a <unknown>\n#1 0x55579acb0a70 <unknown>\n#2 0x55579aca7cf1 <unknown>\n#3 0x55579ac99099 <unknown>\n#4 0x55579ac9ade0 <unknown>\n#5 0x55579ac9943e <unknown>\n#6 0x55579ac98daa <unknown>\n#7 0x55579ac98a85 <unknown>\n#8 0x55579ac968ee <unknown>\n#9 0x55579ac970ca <unknown>\n#10 0x55579acb3f99 <unknown>\n#11 0x55579ad4ed65 <unknown>\n#12 0x55579ad283e2 <unknown>\n#13 0x55579ad4e14f <unknown>\n#14 0x55579ad281b3 <unknown>\n#15 0x55579acf459b <unknown>\n#16 0x55579acf5971 <unknown>\n#17 0x55579b1d625b <unknown>\n#18 0x55579b1d9fa9 <unknown>\n#19 0x55579b1bd339 <unknown>\n#20 0x55579b1dab58 <unknown>\n#21 0x55579b1a1c1f <unknown>\n#22 0x55579b1fe118 <unknown>\n#23 0x55579b1fe2f6 <unknown>\n#24 0x55579b210066 <unknown>\n#25 0x7f244b69caa4 <unknown>\n#26 0x7f244b729c3c <unknown>","time":{"start":1757403361462,"stop":1757403362180,"duration":718}},{"uid":"7c41ed9a00c84e8e","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757403356082,"stop":1757403358948,"duration":2866}},{"uid":"41ea43956bba9ebc","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757403352095,"stop":1757403354369,"duration":2274}},{"uid":"610cd21dc1183cef","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=139.0.7258.154)\nStacktrace:\n#0 0x55b43107408a <unknown>\n#1 0x55b430b13a70 <unknown>\n#2 0x55b430b0acf1 <unknown>\n#3 0x55b430afc099 <unknown>\n#4 0x55b430afdde0 <unknown>\n#5 0x55b430afc43e <unknown>\n#6 0x55b430afbdaa <unknown>\n#7 0x55b430afba85 <unknown>\n#8 0x55b430af98ee <unknown>\n#9 0x55b430afa0ca <unknown>\n#10 0x55b430b16f99 <unknown>\n#11 0x55b430bb1d65 <unknown>\n#12 0x55b430b8b3e2 <unknown>\n#13 0x55b430bb114f <unknown>\n#14 0x55b430b8b1b3 <unknown>\n#15 0x55b430b5759b <unknown>\n#16 0x55b430b58971 <unknown>\n#17 0x55b43103925b <unknown>\n#18 0x55b43103cfa9 <unknown>\n#19 0x55b431020339 <unknown>\n#20 0x55b43103db58 <unknown>\n#21 0x55b431004c1f <unknown>\n#22 0x55b431061118 <unknown>\n#23 0x55b4310612f6 <unknown>\n#24 0x55b431073066 <unknown>\n#25 0x7fc82689caa4 <unknown>\n#26 0x7fc826929c3c <unknown>","time":{"start":1757403350460,"stop":1757403351185,"duration":725}},{"uid":"2413871221a0ca3d","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//3.254.161.142%3A3000/&c=UTF-8&d=Firefox%20can%E2%80%99t%20establish%20a%20connection%20to%20the%20server%20at%203.254.161.142%3A3000.\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:199:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:910:5\ncheckReadyState@chrome://remote/content/marionette/navigate.sys.mjs:59:24\nonNavigation@chrome://remote/content/marionette/navigate.sys.mjs:348:39\nemit@resource://gre/modules/EventEmitter.sys.mjs:156:19\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.sys.mjs:33:25","time":{"start":1757403347748,"stop":1757403349971,"duration":2223}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d81fc935bbd751d3.json","parameterValues":[]}